AN_MAKEVAR([AUTOM4TE], [AC_PROG_AUTOM4TE])
AN_PROGRAM([autom4te], [AC_PROG_AUTOM4TE])
AC_DEFUN_ONCE([AC_PROG_AUTOM4TE],
[AC_CHECK_PROG([AUTOM4TE], [autom4te], `which autom4te`)
AC_SUBST([AUTOM4TE])
])#AC_DEFUN_ONCE
