#! /usr/bin/env sh
# -*- mode: sh-shell; -*-
# ============================================================================ #
#
# Print header dependencies for C/C++ file.
#
#
# ---------------------------------------------------------------------------- #

set -eu
set -o pipefail

# ---------------------------------------------------------------------------- #

_as_me="cdeps";

_version="1.0.0";

_usage_msg="USAGE: $_as_me [OPTION...] FILE [-- CFLAGS]

Print header dependencies for C/C++ file.
";

_help_msg="
OPTIONS:
  -s, --system   Include system headers in output. Equivelant to \`gcc -MM'.
  -C, --cxx      Process as C++ file.
  -D, --defines  Scape \`#ifdef' symbols and set all to 1.
  -h, --help     Print this help message.
  -- CFLAGS      Any flags provided after \`--' are passed as compiler flags.

Compiler tries \`CC' or \`CXX' if \`--cxx' was indicated, if unset these fall
back to \`gcc' and \`g++' respectively.

ENVIRONMENT
  REALPATH            Command used as \`realpath' executable.
  CC                  Command used as \`cc' executable.
  CXX                 Command used as \`c++' executable.
  TR                  Command used as \`tr' executable.
  SED                 Command used as \`sed' executable.
  GREP                Command ugrep as \`grep' executable.
";


# ---------------------------------------------------------------------------- #

usage() {
  if [[ "${1:-}" = "-f" ]]; then
    echo "$_help_msg";
  else
    echo "$_usage_msg";
  fi
}

# ---------------------------------------------------------------------------- #

# @BEGIN_INJECT_UTILS@
: "${REALPATH:=realpath}";
: "${CC:=cc}";
: "${CXX:=c++}";
: "${TR:=tr}";
: "${SED:=sed}";
: "${GREP:=grep}";


# ---------------------------------------------------------------------------- #

# Option settings
_TARGET=;
_SYSDEPS=;
_DO_CXX=;
_DEFINES=;


# ---------------------------------------------------------------------------- #

# Parse options

while [[ "$#" -gt 0 ]]; do
  case "$1" in
  # Split short options such as `-abc' -> `-a -b -c'
  -[^-]?*)
    _arg="$1";
    declare -a _args;
    _args=();
    shift;
    _i=1;
    while [[ "$_i" -lt "${#_arg}" ]]; do
      _args+=("-${_arg:$_i:1}");
      _i="$((_i + 1))";
    done
    set -- "${_args[@]}" "$@";
    unset _arg _args _i;
    continue;
  ;;
  --*=*)
    _arg="$1";
    shift;
    set -- "${_arg%%=*}" "${_arg#*=}" "$@";
    unset _arg;
    continue;
  ;;
  -u|--usage)   usage;    exit 0; ;;
  -h|--help)    usage -f; exit 0; ;;
  -v|--version) echo "$_version"; exit 0; ;;
  --)           shift; break; ;;
  -s|--system)  _SYSDEPS=:; ;;
  -C|--cxx)     _DO_CXX=:; ;;
  -D|--defines) _DEFINES=:; ;;
  -?|--*)
    echo "$_as_me: Unrecognized option: \`$1'" >&2;
    usage -f >&2;
    exit 1;
  ;;
  *)
    if [[ -z "$_TARGET" ]]; then
      _TARGET="$1";
    else
      echo "$_as_me: Unexpected argument(s) \`$*'" >&2;
      usage -f >&2
      exit 1
    fi
  ;;
  esac
  shift
done

# ---------------------------------------------------------------------------- #

# Strip off leading `./' or any other wonky pathname stuff that `CC -M' drops.
_TARGET="$( realpath --relative-to "$PWD" "$_TARGET"; )";


# Remaining args are considered compiler flags
if test "$#" -gt 0; then
  CFLAGS="$*";
fi


# ---------------------------------------------------------------------------- #

if test "$_SYSDEPS"; then
  CFLAGS="${CFLAGS+$CFLAGS }-M";
else
  CFLAGS="${CFLAGS+$CFLAGS }-MM";
fi


# ---------------------------------------------------------------------------- #

# Select compiler
if test "$_DO_CXX"; then
  COMPILER="${CXX:-$( command -v c++; )}";
else
  COMPILER="${CC:-$( command -v cc; )}";
fi


# ---------------------------------------------------------------------------- #

_getifnames() {
  ifnames "$_TARGET" 2>/dev/null|cut -d' ' -f1;
}


_joinlines() {
  $SED ':x; /\\$/ { N; s/\\\n//; tx }' /dev/stdin;
}

_wslines() {
  $TR -s '\t' ' ' < /dev/stdin         \
    |$SED -e 's/^ \+//' -e 's/ \+$//'  \
    |$TR ' ' '\n';
}

_getdeps() {
  # Remove the target file and fake target.
  # Suppress debug output from CPP.
  $COMPILER -MT '' "$_TARGET" "$CFLAGS"|sed -e 's/^: //';
}

_getdeps_post() {
  _getdeps|_joinlines|_wslines|grep -v "^${_TARGET#\.#\\\.}\$";
}


# ---------------------------------------------------------------------------- #

# Scrape `#ifdef' symbols and set all of them to 1 using `-D<NAME>'.
# This is far from exhaustive considering that combinations of these symbols
# might be incompatible; but this covers a large number of use cases.
if test "$_DEFINES"; then
  # FIXME: Permutate over defines
  #CFLAGS_SAVED="${CFLAGS}";
  for d in $( _getifnames; ); do
    CFLAGS="${CFLAGS+$CFLAGS }-D$d";
  done
fi


# ---------------------------------------------------------------------------- #

_getdeps_post;


# ---------------------------------------------------------------------------- #
#
#
#
# ============================================================================ #
# vim: set filetype=sh :
