#! /usr/bin/env sh
# -*- mode: sh-mode; -*-
# ============================================================================ #


# ---------------------------------------------------------------------------- #

function usage() {
MESSAGE="\
Usage: cuts OPTION... [FILE]
Print selected parts of FILE to standard output.

With no FILE, or when FILE is -, read standard input.

Mandatory arguments to long options are mandatory for short options too.
  -d, --delimiters=DELIMS   use DELIMS instead of TAB/SPACE for field delimiters
  -f, --fields=LIST         select only these fields;  also print any line
                            that contains no delimiter character.
Each LIST is made up of one range, or many ranges separated by commas.
Selected input is written in the same order that it is read, and is written
exactly once.
Each range is one of:

  N     N'th byte, character or field, counted from 1
  N-    from N'th byte, character or field, to end of line
  N-M   from N'th to M'th (included) byte, character or field
  -M    from first to M'th (included) byte, character or field

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/cut>
or available locally via: info '(coreutils) cut invocation'";
  echo "${MESSAGE}";
}


# ---------------------------------------------------------------------------- #

field=1;
delims=' \t';

while getopts hf:d: a; do
  case "${a}" in
    d)   delims="${OPTARG}"; ;;
    f)   field="${OPTARG}";  ;;
    h)   usage; exit 0;      ;;
    [?]) usage >&2; exit 1;  ;;
  esac
done
shift $(( ${OPTIND} - 1 ));


# ---------------------------------------------------------------------------- #

cat ${@:--}                                                                    \
  |sed 's/['"${delims[@]}"']\+/'"${delims[@]:0:1}"'/g'                         \
  |cut -d "${delims[@]:0:1}" -f "${field}";


# ---------------------------------------------------------------------------- #



# ============================================================================ #
# vim: set filetype=sh :
