#! /usr/bin/env sh

test -z "$MAKE" && MAKE=$( which make; );
test -z "$GREP" && GREP=$( which grep; );
test -z "$SED" && SED=$( which sed; );

FLAGS='-qpRrsi';
IGNORE_ENV='-i';

while test "${#}" -gt 0; do
  if test "${1}" = '-a' || test "${1}" = '--all'; then
    FLAGS='-qpsi';
    shift;
  elif test "${1}" = '-I' || test "${1}" = '--keep-env'; then
    IGNORE_ENV='';
    shift;
  else
    break;
  fi
done

eval /usr/bin/env ${IGNORE_ENV}                                    \
  ${MAKE} ${FLAGS} ${@}                                            \
    |${GREP} '^[a-zA-Z_\.][a-zA-Z_\.0-9]* *[ ?:]*='                \
    |${SED} 's/^\([a-zA-Z_\.][a-zA-Z_\.0-9]*\) *[ ?:]*= */\1 = /';
