#! /usr/bin/env sh

FLAGS='-qpRrsi';
if test "${#} -gt 0; then
  if test "${1}" = '-a' || test "${1}" = '--all'; then
    FLAGS='-qpsi';
    shift;
  fi
fi

make ${FLAGS} ${@}                              \
  |grep '^[a-zA-Z_\.][a-zA-Z_\.0-9]* *[ ?:]*='  \
  |sed 's/^\([a-zA-Z_\.][a-zA-Z_\.0-9]*\) *[ ?:]*= */\1 = /'
