#! /usr/bin/env bash
# ============================================================================ #
#
# Checks if programs are available in PATH.
# USAGE: has-programs OPTIONS [--] PROG...
#
# See `usage' function below for additional details.
#
#
# ---------------------------------------------------------------------------- #

set -eu;

as_me="has-programs";

: "${COMMAND=command}";
: "${WHICH=$COMMAND $COMMAND -v}";
: "${TEST=test}";
: "${READLINK=readlink}";
: "${PRINTF=printf}";
: "${ECHO=$PRINTF %s\n}";
: "${TRUE=:}";

: "${QUIET=}";
: "${OUTPUT_YN=}";
: "${IGNORE=}";


# ---------------------------------------------------------------------------- #

usage() {
  $ECHO "\
Checks if programs are available in PATH.
  Prints \"PROG: found at PATH\" or \"PROG: not found\" by default.
  Prints \"PROG: yes\" or \"PROG: no\" if the -b or --yes-no flag are given.
  Sets exit status to the number of programs which were not found.
USAGE: $as_me OPTIONS [--] PROG...
OPTIONS
  -h,--help    Print this help message
  -b,--yes-no  Only print yes/no foreach program.
  -q,--quiet   Print nothing, set exit status to 0 if all programs are found,
               or the number of programs which could not be found otherwise.
  -i,--ignore  Do not return a non-zero exit status.
";
}


# ---------------------------------------------------------------------------- #

while $TEST "$#" -gt 0; do
  case "$1" in
    -b|--yes-no)
      OUTPUT_YN="$TRUE";
    ;;
    -h|--help)
      usage;
      exit 0;
    ;;
    -q|--quiet)
      QUIET="$TRUE";
    ;;
    -i|--ignore)
      IGNORE="$TRUE";
    ;;
    --)
      shift;
      break;
    ;;
    *)
      break;
    ;;
  esac
  shift;
done

if $TEST "$#" -lt 1; then
  $ECHO "$as_me: You must provide the name of a program to search for." >&2;
  usage;
  exit 1;
fi


# ---------------------------------------------------------------------------- #

has_prog() {
  $TEST -n "$( $WHICH "$1"; )";
}

prog_path() {
  $READLINK -f "$( $WHICH "$1"; )";
}

check_prog() {
  if has_prog "$1"; then
    if $TEST "$OUTPUT_YN"; then
      $ECHO "$1: yes";
    else
      $ECHO "$1: found at $( prog_path "$1"; )";
    fi
    return 0;
  else
    if $TEST "$OUTPUT_YN"; then
      $ECHO "$1: no";
    else
      $ECHO "$1: not found";
    fi
    return 1;
  fi
}


# ---------------------------------------------------------------------------- #

if $TEST "$QUIET"; then
  CHECK_CMD=has_prog;
else
  CHECK_CMD=check_prog;
fi

NOT_FOUND=0;

while $TEST "$#" -gt 0; do
  if ! $CHECK_CMD "$1"; then
    NOT_FOUND="$(( NOT_FOUND + 1 ))";
  fi
  shift;
done

if $TEST "$IGNORE"; then
  exit 0;
else
  exit $NOT_FOUND;
fi


# ---------------------------------------------------------------------------- #
#
#
#
# ============================================================================ #
# vim: set filetype=sh :
