#! /bin/env sh
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Copyright (c) 1990, 1993
#   The Regents of the University of California.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#   @(#)lorder.sh   8.1 (Berkeley) 6/6/93
#
# $FreeBSD$
#
#
# ============================================================================ #
#
# This version of `lorder' was ported from FreeBSD by
# Alex Ameen
#
# "Port" version number is : L-1.0.0
#
#
# ---------------------------------------------------------------------------- #
 
# Only one argument is a special case, just output the name twice
case ${#} in
  0) echo "usage: lorder FILE..."; exit ;;
  1) echo ${1} ${1};               exit ;;
esac
 
# Temporary files
R=$( mktemp -t _reference_-XXXX; );
S=$( mktemp -t _symbol_-XXXX; );
 
# Remove temporary files on HUP, INT, QUIT, PIPE, TERM
trap "rm -f $R $S $T; exit 1;" 1 2 3 13 15;
 

# ---------------------------------------------------------------------------- #

# Make sure all the files get into the output.
for i in ${*}; do
  echo ${i} ${i};
done
 

# ---------------------------------------------------------------------------- #
#
# If the line has " [TDWBVRui] " it's a globally defined symbol, put it
# into the symbol file.
# `man nm;' has detailed information about the meaning of each type.
#
# If the line has " U " it's a globally undefined symbol, put it into
# the reference file.
#
# Shared Objects are not detected in a robust manner.
# If you find yourself needing more accurate SO detection feel free
# make those changes here before the list `SO_FILES' is processed.
declare -a SO_FILES;
SO_FILES=( $( echo ${@}|tr ' ' '\n'|grep '^.*\.so.*'; ) );
( nm -go ${*} 2>/dev/null; nm -goD ${SO_FILES} 2>/dev/null; )| sed "
  / [TDWBVRui] / {
    s/:.* [TDWBVRui] / /
    w $S
    d
  }
  / U / {
    s/:.* U / /
    w $R
  }
  d
";


# ---------------------------------------------------------------------------- #
 
export LC_ALL=C
# eliminate references that can be resolved by the same library.
if [ $( expr "$*" : '.*\.a\b' ) -ne 0 ]; then
  sort -u -o $S $S;
  sort -u -o $R $R;
  T=$( mktemp -t _temp_-XXXX; );
  comm -23 $R $S >$T;
  mv $T $R;
fi
 

# ---------------------------------------------------------------------------- #

# Sort references and symbols on the second field (the symbol),
# join on that field, and print out the file names.
# Finally remove redundant lines after "joining".
sort -k 2 -o $R $R;
sort -k 2 -o $S $S;
join -j 2 -o 1.1 2.1 $R $S|sort|uniq;
 

# ---------------------------------------------------------------------------- #

# Cleanup
rm -f $R $S;
 
 
# Changelog: ================================================================= #
#
# 1.0.0:
#   * Added additional symbol types that `nm' uses to mark global symbols.
#     Notably many of these symbols appear in `libc.so.6', and any libraries
#     which use GNU Unique features.
#     So earlier versions of this script would fail to detect some dependencies
#     as a result.
#
#
# ---------------------------------------------------------------------------- #
 


# ============================================================================ #
# vim: set filetype=sh :
