#! /usr/bin/env sh
set -e;
as_me=mangle;
SYMS=$( mktemp -t ${as_me}-XXXXXX; );
CFILE=$( mktemp -t ${as_me}-XXXXXX.cpp; );
OFILE=$( mktemp -t ${as_me}-XXXXXX.o; );
trap "rm -f ${SYMS} ${CFILE} ${OFILE}; exit 1;" 1 2 3 13 15;

if test ${#} -lt 1; then
  cat - > ${SYMS};
else
  echo "${@}" > ${SYMS};
fi

cat ${SYMS}|sed 's/$/;/' > ${CFILE};
echo -e 'int main( void ) {\n  void * __MANGLER = nullptr;' >> ${CFILE};

cat ${SYMS}                                                                    \
  |sed 's/^.* \([a-zA-Z_][a-zA-Z_:<>~0-9]\+\)(.*$/  __MANGLER = (void *) \1;/' \
       >> ${CFILE};

echo -e '  return 0;\n}' >> ${CFILE};
g++ -c ${CFILE} -o ${OFILE};

nm -uP ${OFILE}|cut -d' ' -f1;
rm -f ${SYMS} ${CFILE} ${OFILE};
