.TH WSMERGE 1 \" -*- nroff -*-
.SH NAME
wsmerge \- replace repeated spaces or tabs with a single space
.SH SYNOPSYS
.B wsmerge
[\fI\,FILE\/\fR]
.SH DESCRIPTION
.PP
Replace repeated tab or space characters with a single space.
.PP
With no FILE, or when file is \-, read standard input.
.SH AUTHOR
Written by Alex Ameen.
.SH "REPORTING BUGS"
Bugs may be reported to the issue list:
<https://github.com/aakropotkin/ak-core/>
.SH "SEE ALSO"
.BR tr (1),
.BR sed (1)
.PP
.SH COPYRIGHT
Copyright \(co 2021-2022 Free Software Foundation, Inc.   License  GPLv3+:
.br
GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This  is  free  software:  you  are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
