name: AK-Core Lint
on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --impure --configure
    - run: nix shell nixpkgs#autoconf nixpkgs#automake nixpkgs#libtool nixpkgs#shellcheck -c 'make -C src/sh-scripts check-local'
