name: AK-Core Lint
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: |
        set -eu
        exec nix develop --impure <<EOF
        unpackPhase
        cd $sourceRoot
        patchPhase
        configurePhase
        make -C src/sh-scripts/test check-local
        EOF
