name: AK-Core Flake Build
on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    defaults:
      run:
        shell: bash
    name: Build
    runs-on: ubuntu-latest
    env:
      SYSTEM: x86_64-linux
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build --system "$SYSTEM"
    - run: nix flake check --system "$SYSTEM"
