name: AK-Core Basic Tests
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build --impure
    - run: nix flake check --impure
    - run: nix shell --impure nixpkgs#bashInteractive -c bash -c "echo OK"
